language: node_js
node_js:
- 0.1
env:
  matrix:
  - JOB=unit-stable
  - JOB=unit-dev
  global:
  - CHROME_BIN=/usr/bin/google-chrome
  - secure: NJt0LRmY2HoMw4QuTc+8MhDfSCTTuXe0kE7pC1flbhQOi/g6sdVX57b/4OZzBXRKG1oq/URX4FMeVgSuFQvTaEad0qsTPoGji/Mmk61LRtE/Mbo/H7v5P2tyGPPJ5S25C/xFo42cKDyzFU8Uv+5W2Htijsa3xt4VfAWcDmZJjuA=
before_install:
- export DISPLAY=:99.0
- ./scripts/travis/install.sh
before_script:
- ./scripts/travis/setup.sh
script:
- ./scripts/travis/build.sh
after_script:
- ./scripts/travis/publish-docs.sh
