#!/bin/sh

# Usage: pick-pr <pr-number>
#
# Takes a PR and cherry-picks it into the current branch.
# Assumes you have a "pr" branch set up.

set -e

PR=$1
echo "Picking PR $1"

for sha in $(git rev-list --reverse pr/$PR ^upstream/master); do
	git cherry-pick $sha;
done

export PR
export GIT_EDITOR=$(dirname $0)/pick-pr-editor
git commit --amend